# COMMENT: This a rule for showing project live demos
[[redirects]]
  from = "/projects/agency/live-demo"
  to = "https://project-agency.netlify.com"
  status = 200
  force = true

# COMMENT: This a rule for showing case studies
[[redirects]]
  from = "/projects/agency/case-study"
  to = "https://project-case-studies.netlify.com/case-studies/agency.html"
  status = 200
  force = true

# COMMENT: This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
